export type UserRole = "CUSTOMER" | "ADMIN" | "SUPER_ADMIN";

export const permissions = {
  customer: [
    "auth:view_profile",
    "auth:update_profile",
    "auth:manage_2fa",
    "auth:view_login_history",
    "product:read",
    "quote:create",
    "quote:read_own",
    "quote:save",
    "quote:download_pdf",
    "quote:convert_to_order",
    "gerber:upload",
    "gerber:preview",
    "gerber:download_own",
    "gerber:delete_own",
    "order:create",
    "order:read_own",
    "order:cancel_own",
    "order:reorder",
    "order:download_invoice",
    "order:download_report",
    "payment:pay",
    "payment:read_own",
    "payment:download_receipt",
    "support:create_ticket",
    "support:reply_own_ticket",
    "support:close_own_ticket",
    "notification:read_own",
  ],
  admin: [
    "product:create",
    "product:update",
    "product:delete",
    "product:manage_categories",
    "product:manage_inventory",
    "quote:review",
    "quote:approve",
    "quote:reject",
    "quote:edit_pricing",
    "gerber:review",
    "gerber:approve",
    "gerber:reject",
    "gerber:request_revision",
    "order:read_all",
    "order:update_status",
    "order:assign_production",
    "order:update_shipping",
    "customer:read",
    "customer:verify",
    "customer:block",
    "customer:unblock",
    "production:move_to_production",
    "production:assign_engineer",
    "production:assign_qc",
    "production:update_progress",
    "payment:read_all",
    "payment:verify",
    "payment:refund",
    "support:manage_tickets",
    "support:manage_live_chat",
    "coupon:create",
    "coupon:update",
    "coupon:delete",
    "review:approve",
    "review:delete_spam",
    "notification:send",
    "notification:broadcast",
    "notification:send_promotional_email",
    "shipping:generate_label",
    "shipping:manage_carriers",
  ],
  superAdmin: [
    "admin:create",
    "admin:update",
    "admin:delete",
    "admin:suspend",
    "admin:assign_permissions",
    "role:create",
    "role:update",
    "role:delete",
    "role:assign_permissions",
    "system:manage_settings",
    "system:manage_branding",
    "system:manage_smtp",
    "system:manage_security",
    "system:maintenance_mode",
    "system:monitor_health",
    "payment:manage_gateways",
    "pricing:manage_formula",
    "pricing:manage_materials",
    "pricing:manage_layers",
    "pricing:manage_assembly",
    "pricing:manage_shipping",
    "localization:manage_currency",
    "localization:manage_language",
    "localization:manage_country",
    "localization:manage_tax_rules",
    "analytics:revenue",
    "analytics:customer",
    "analytics:product",
    "analytics:country",
    "analytics:conversion",
    "analytics:marketing",
    "cms:manage_blogs",
    "cms:manage_pages",
    "cms:manage_faqs",
    "cms:manage_news",
    "cms:manage_announcements",
    "security:view_login_logs",
    "security:view_activity_logs",
    "security:view_security_events",
    "security:view_failed_logins",
    "security:view_suspicious_activities",
    "backup:create",
    "backup:restore",
    "backup:download",
    "audit:read_all",
  ],
} as const;

export const defaultRolePermissions: Record<UserRole, string[]> = {
  CUSTOMER: [...permissions.customer],
  ADMIN: [...permissions.admin],
  SUPER_ADMIN: [...permissions.customer, ...permissions.admin, ...permissions.superAdmin],
};

export const roleLabels: Record<UserRole, string> = {
  CUSTOMER: "Customer",
  ADMIN: "Admin",
  SUPER_ADMIN: "Super Admin",
};

export function hasPermission(userPermissions: string[] | undefined, permission: string) {
  return Boolean(userPermissions?.includes(permission));
}
